package chart

import (
	"html/template"
	"io"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ .Title }} — dq</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
    <style>
        :root {
            --bg: #0f0f23;
            --surface: #16213e;
            --border: rgba(255,255,255,0.06);
            --text: #e0e0e0;
            --muted: #666;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            background: var(--bg);
            color: var(--text);
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        header {
            padding: 14px 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid var(--border);
            background: var(--surface);
        }
        header h1 {
            font-size: 15px;
            font-weight: 600;
            letter-spacing: -0.01em;
        }
        header .meta {
            font-size: 12px;
            color: var(--muted);
            font-family: 'SF Mono', 'Fira Code', monospace;
        }
        #chart {
            flex: 1;
            min-height: 0;
        }
        footer {
            padding: 8px 24px;
            font-size: 11px;
            color: var(--muted);
            text-align: right;
            border-top: 1px solid var(--border);
            font-family: 'SF Mono', 'Fira Code', monospace;
        }
    </style>
</head>
<body>
    <header>
        <h1>{{ .Title }}</h1>
        <span class="meta">{{ .RowCount }} rows &middot; {{ .ChartType }}</span>
    </header>
    <div id="chart"></div>
    <footer>generated by dq</footer>
    <script>
        var chart = echarts.init(document.getElementById('chart'), 'dark');
        chart.setOption({{ .OptionJSON }});
        window.addEventListener('resize', function() { chart.resize(); });
    </script>
</body>
</html>`

// TemplateData holds values injected into the HTML template.
type TemplateData struct {
	Title      string
	ChartType  string
	RowCount   int
	OptionJSON template.JS // safe pre-serialized JavaScript
}

var chartTmpl = template.Must(template.New("chart").Parse(htmlTemplate))

// Render writes the chart HTML to the given writer.
func Render(w io.Writer, data TemplateData) error {
	return chartTmpl.Execute(w, data)
}
